"""Security audit trail.

Answers one question: *who asked for what, on whose authority, what did NEXUS
decide, and what ended up executing?* Every entry carries those fields, so the
question is answerable by filtering rather than by reconstructing.

Three properties are deliberate and each one exists because of a specific
failure it prevents:

**Records are append-only from the application's point of view.** Nothing in the
agent path holds a handle that can delete or rewrite an entry. The LLM, a tool
and the sandbox have no route to this object at all -- the audit log is written
by the layers that *make* decisions, and read by operators, not by the agent.
That is the separation between application data and security audit data: an agent
can write a task, and writing a task cannot erase the record that it tried.

**Secrets never enter an entry.** Every free-text field passes through
:mod:`app.application.security.secrets` on the way in. A refusal is useless if it
also leaks the credential the caller was reaching for, and an audit log is the
one place that is guaranteed to be retained.

**Identifiers, not payloads.** Entries carry ids, tool names, decisions, risk
levels and reasons. Memory content, tool arguments and stack traces do not
appear, because the log is retained far longer than any of them is meant to live.
"""

from __future__ import annotations

import logging
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Deque, Iterable

from app.application.security.secrets import redact as redact_text
from app.domain.entities._common import utc_now
from app.domain.value_objects.entity_id import EntityId
from app.domain.value_objects.runtime_event_type import AuthorizationEventType

logger = logging.getLogger("nexus.security.audit")

#: Bound on the in-memory ring. The log is an operational aid, not a compliance
#: store: an unbounded list is itself a memory-exhaustion vector, reachable by
#: anyone who can provoke denials.
DEFAULT_CAPACITY = 2_000

#: Longest reason string retained. Reasons are generated by our own policies and
#: are short by construction; the cap is here so a future caller cannot turn the
#: audit log into arbitrary data storage.
MAX_REASON_CHARS = 300


@dataclass(frozen=True, slots=True)
class AuditEntry:
    """One decision, recorded once."""

    event: AuthorizationEventType | str
    #: Who the request was made on behalf of. Never a client-supplied string.
    user_id: str | None = None
    agent_id: str | None = None
    agent_run_id: str | None = None
    tool_name: str | None = None
    action_name: str | None = None
    decision: str | None = None
    risk_level: str | None = None
    permission_id: str | None = None
    result: str | None = None
    reason: str | None = None
    timestamp: datetime = field(default_factory=utc_now)

    def as_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat(),
            "event": str(self.event),
            "user_id": self.user_id,
            "agent_id": self.agent_id,
            "agent_run_id": self.agent_run_id,
            "tool_name": self.tool_name,
            "action_name": self.action_name,
            "decision": self.decision,
            "risk_level": self.risk_level,
            "permission_id": self.permission_id,
            "result": self.result,
            "reason": self.reason,
        }


class SecurityAuditLog:
    """Append-only record of authorization decisions.

    Synchronous and in-process. It is written on the decision path, so it must
    not await I/O a decision depends on; the log is a record of what happened,
    never a precondition for it.
    """

    def __init__(self, capacity: int = DEFAULT_CAPACITY) -> None:
        self._entries: Deque[AuditEntry] = deque(maxlen=capacity)
        self._monotonic = 0

    def record(
        self,
        event: AuthorizationEventType | str,
        *,
        user_id: EntityId | str | None = None,
        agent_id: EntityId | str | None = None,
        agent_run_id: EntityId | str | None = None,
        tool_name: str | None = None,
        action_name: str | None = None,
        decision: str | None = None,
        risk_level: str | None = None,
        permission_id: EntityId | str | None = None,
        result: str | None = None,
        reason: str | None = None,
        #: Extra structured fields for the log line only. Accepted and ignored by
        #: the in-memory entry on purpose: the entry is a fixed-shape record, and
        #: letting callers widen it is how an audit trail becomes a data store.
        extra: dict[str, Any] | None = None,
    ) -> AuditEntry:
        entry = AuditEntry(
            event=event,
            user_id=_as_id(user_id),
            agent_id=_as_id(agent_id),
            agent_run_id=_as_id(agent_run_id),
            tool_name=_short(tool_name),
            action_name=_short(action_name),
            decision=_short(decision),
            risk_level=_short(risk_level),
            permission_id=_as_id(permission_id),
            result=_short(result),
            # Redaction happens here rather than at each call site. A control
            # that every caller must remember is a control that will eventually
            # be forgotten at the one call site that matters.
            reason=_short(reason, limit=MAX_REASON_CHARS, scrub=True),
        )
        self._entries.append(entry)
        self._monotonic += 1
        # ``extra`` carries the structured record for anything shipping these logs
        # onward; the human-readable line stays short and free of payloads.
        logger.info(
            "%s",
            entry.event,
            extra={
                "security_audit": entry.as_dict(),
                "user_id": entry.user_id,
                "agent_id": entry.agent_id,
                "agent_run_id": entry.agent_run_id,
                "tool_name": entry.tool_name,
                "decision": entry.decision,
                "reason": entry.reason,
            },
        )
        return entry

    # -- read side ---------------------------------------------------------

    def entries(self) -> tuple[AuditEntry, ...]:
        return tuple(self._entries)

    def find(
        self,
        *,
        event: AuthorizationEventType | str | None = None,
        tool_name: str | None = None,
        agent_run_id: EntityId | str | None = None,
        user_id: EntityId | str | None = None,
    ) -> tuple[AuditEntry, ...]:
        """Filter the trail. Used by tests and by incident triage."""
        wanted_event = str(event) if event is not None else None
        wanted_run = _as_id(agent_run_id)
        wanted_user = _as_id(user_id)
        return tuple(
            entry
            for entry in self._entries
            if (wanted_event is None or str(entry.event) == wanted_event)
            and (tool_name is None or entry.tool_name == tool_name)
            and (wanted_run is None or entry.agent_run_id == wanted_run)
            and (wanted_user is None or entry.user_id == wanted_user)
        )

    def __len__(self) -> int:
        return len(self._entries)


class NullAuditLog(SecurityAuditLog):
    """Writes nothing. For tests that assert on behaviour, not on the trail."""

    def __init__(self) -> None:  # noqa: D107 - deliberately skips super().__init__
        self._entries = deque(maxlen=1)
        self._monotonic = 0

    def record(self, event: AuthorizationEventType | str, **kwargs: Any) -> AuditEntry:  # noqa: ANN401
        entry = AuditEntry(event=event, **_safe_fields(kwargs))
        self._entries.append(entry)
        return entry


def _safe_fields(kwargs: dict[str, Any]) -> dict[str, Any]:
    allowed = {
        "user_id",
        "agent_id",
        "agent_run_id",
        "tool_name",
        "action_name",
        "decision",
        "risk_level",
        "permission_id",
        "result",
        "reason",
    }
    return {
        key: value
        for key, value in kwargs.items()
        if key in allowed and isinstance(value, (str, type(None)))
    }


def _as_id(value: EntityId | str | None) -> str | None:
    if value is None:
        return None
    return str(value)


def _short(value: Any, limit: int = 120, *, scrub: bool = False) -> str | None:
    if value is None:
        return None
    text = str(value)
    if scrub:
        text = redact_text(text)
    if len(text) > limit:
        text = text[: limit - 1] + "…"
    return text


def summarize(entries: Iterable[AuditEntry]) -> dict[str, int]:
    """Count entries per event type. Cheap enough to call from a health route."""
    counts: dict[str, int] = {}
    for entry in entries:
        key = str(entry.event)
        counts[key] = counts.get(key, 0) + 1
    return counts


__all__ = ("AuditEntry", "NullAuditLog", "SecurityAuditLog", "summarize")