from enum import StrEnum


class AgentRunStatus(StrEnum):
    CREATED = "CREATED"
    CONTEXT_LOADING = "CONTEXT_LOADING"
    PLANNING = "PLANNING"
    WAITING_PERMISSION = "WAITING_PERMISSION"
    EXECUTING = "EXECUTING"
    OBSERVING = "OBSERVING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
