from enum import StrEnum


class ToolErrorCode(StrEnum):
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    FORBIDDEN_ARGUMENTS = "FORBIDDEN_ARGUMENTS"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    REPOSITORY_ERROR = "REPOSITORY_ERROR"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_TRANSITION_INVALID = "TASK_TRANSITION_INVALID"
    MEMORY_NOT_FOUND = "MEMORY_NOT_FOUND"
    MEMORY_BLOCKED = "MEMORY_BLOCKED"
